### ISSUE TITLE
Set color v1.3.11

### ISSUE THREAD

**Issue by suraj-afrogleap** [sephiroth74/android-target-tooltip#25] opened 2016-01-26 12:55 UTC
From the docs i could get an idea how to specify the text color for the tooltip. Could you provide some more information please ?

**Comment by sytolk** [comment] 2016-01-27 08:26
Duplicate of this
https://github.com/sephiroth74/android-target-tooltip/issues/11

**Closed** 2016-01-27 09:57 UTC
